language: python

# Cache PlatformIO packages using Travis CI container-based infrastructure
sudo: false
cache:
    directories:
        - "~/.platformio"

env:
    - PLATFORMIO_CI_SRC=src

install:
    - pip install -U platformio
    - platformio update

addons:
    apt:
        packages:
            - doxygen

script:
    # check for trailing white spaces (comparing with first commit in git log)
    - git diff --check `git rev-list HEAD | tail -n 1`..$TRAVIS_BRANCH
    - platformio run -e mppt-2420-lc-v0.10 -e mppt-1210-hus-v0.7 -e pwm-2420-lus-v0.3
    - platformio test -e unit-test-native
    - platformio check -e mppt-1210-hus-v0.7 -e pwm-2420-lus-v0.3
    - doxygen Doxyfile

deploy:
    provider: pages
    skip_cleanup: true
    local_dir: html
    github_token: $GH_REPO_TOKEN
    on:
        repo: LibreSolar/charge-controller-firmware
        branch: master
